---
apiVersion: v1
kind: Service
metadata:
  name: djangoweb
spec:
  selector:
    app: djangoweb
  ports:
  - name: default
    protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 31111
  type: LoadBalancer



---
apiVersion: v1
kind: Deployment
metadata:
  name: djangotest
  labels:
    app: djangotest
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: djangotest
  template:
    metadata:
      labels:
        pod: djangotest
    spec:
      containers:
        - name: djangotest
          image: oltidev/djangoweb
          ports:
            - containerPort: 8000
