---
kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    pod: djangotest
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30011
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangotest
  labels:
    app: djangotest
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: djangotest
  template:
    metadata:
      labels:
        pod: djangotest
    spec:
      containers:
        - name: djangotest
          image: oltidev/djangoweb
          ports:
            - containerPort: 8000
