# Generated by Django 2.0.7 on 2018-09-25 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmesregistraton',
            name='id_reg_farmer',
            field=models.CharField(default='notset', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmesregistraton',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 25, 8, 34, 50, 819741, tzinfo=utc)),
        ),
    ]
