# Generated by Django 2.0.7 on 2018-09-28 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20180925_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmesregistraton',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 28, 20, 32, 56, 326326, tzinfo=utc)),
        ),
    ]
