# Generated by Django 2.0.7 on 2018-10-07 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_auto_20181007_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmesregistraton',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 7, 15, 7, 56, 398816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postproduct',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 7, 15, 7, 56, 399818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postproduct',
            name='image',
            field=models.ImageField(blank=True, default='notset', upload_to='farmers_post'),
        ),
        migrations.AlterField(
            model_name='soldproduct',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 7, 15, 7, 56, 399818, tzinfo=utc)),
        ),
    ]
